<H1>DAV : Assignment 1 (Numpy)
<BR>Name : DHIRENDRA KUMAR PATEL
<BR>ROLL : 16027<H1>

---
<h2>1. What factors should you consider when deciding whether to use NumPy or Python lists for a specific task?
<br>Can you provide examples of tasks that are best suited for NumPy, and others
for which Python lists are sufficient?</h2>

###Ans: Following factors should be considered when deciding whether to use NumPy or Python lists for a specific task:
<ol>a. Data Type - Numpy array are designed for storing and manipulating homogeneous data. While python liste can comes store at any type of data, the flexibility of lists comes at a performance cost.
<br>b. Performance - Numpy arrays are typically much faster than python lists for numerical operations because they are stored in contegeous memory and are optimised for vectorised operations.
<br>c. Memory Uses: Numpy arrays can be more efficient in terms of memory wage, especially for large data sets.
<br>d. Ease of use:- Python list are generally easier to use than Numpy for beginners.
</ol>

---
##2. Explain Broadcasting in numpy and Create 2 dimension array with user input and validate for implementation of broadcasting on arithmetic operation (+,-,*,/,%). Show proper results on every operation.

###Ans: Broadcasting in NumPy allows to perform element-wise operations on arrays of different shapes and sizes and eliminates the need for explicit looping over array elements.

In [ ]:
import numpy as np
rows=int(input("Enter no. of rows :"))
cols=int(input("Enter no. of columns :"))
arr2=np.zeros((rows,cols),dtype=float)
for x in range(rows):
  for y in range(cols):
    arr2[x][y]=float(input(f"Enter the element at {x},{y} :"))
print("Array : \n",arr2)
print("\nBroadcast Addition (+5) : \n",arr2+5)
print("\nBroadcast Subtraction (-3) : \n",arr2-3)
print("\nBroadcast Multiplication (*10) : \n",arr2*10)
print("\nBroadcast Division (/5) : \n",arr2/5)
print("\nBroadcast Modulo(returns remainder) (%3) : \n",arr2%3)

Enter no. of rows :2
Enter no. of columns :2
Enter the element at 0,0 :2
Enter the element at 0,1 :3
Enter the element at 1,0 :4
Enter the element at 1,1 :5
Array : 
 [[2. 3.]
 [4. 5.]]

Broadcast Addition (+5) : 
 [[ 7.  8.]
 [ 9. 10.]]

Broadcast Subtraction (-3) : 
 [[-1.  0.]
 [ 1.  2.]]

Broadcast Multiplication (*10) : 
 [[20. 30.]
 [40. 50.]]

Broadcast Division (/5) : 
 [[0.4 0.6]
 [0.8 1. ]]

Broadcast Modulo(returns remainder) (%3) : 
 [[2. 0.]
 [1. 2.]]


---
##3. Explain and Calculate inner, outer, and cross products of matrices and vectors using NumPy

###Ans: <ul><li>Inner Product (Dot Product): The inner product often refers to the dot product and it calculates the sum of the pairwise products of the two vectors.</ul>




In [ ]:
arr3a=np.arange(1,10).reshape((3,3))
arr3b=a*2
print("a: \n", arr3a, "\n\nb: \n", arr3b)
print("\nDot Product :\n", np.dot(arr3a,arr3b))

a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

b: 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Dot Product :
 [[ 60.  72.  84.]
 [132. 162. 192.]
 [204. 252. 300.]]


<ul><li>Outer Product: The outer product calculates a matrix where each element is the product of corresponding elements of the two vectors.</ul>


In [ ]:
print("\nOuter Product :\n", np.outer(arr3a,arr3b))


Outer Product :
 [[  2.   4.   6.   8.  10.  12.  14.  16.  18.]
 [  4.   8.  12.  16.  20.  24.  28.  32.  36.]
 [  6.  12.  18.  24.  30.  36.  42.  48.  54.]
 [  8.  16.  24.  32.  40.  48.  56.  64.  72.]
 [ 10.  20.  30.  40.  50.  60.  70.  80.  90.]
 [ 12.  24.  36.  48.  60.  72.  84.  96. 108.]
 [ 14.  28.  42.  56.  70.  84.  98. 112. 126.]
 [ 16.  32.  48.  64.  80.  96. 112. 128. 144.]
 [ 18.  36.  54.  72.  90. 108. 126. 144. 162.]]


<ul><li>Cross Product: The cross product of two vectors, A and B is a new vector perpendicular to the plane containing A and B. The magnitude of the cross product is equal to the area of the parallelogram formed by A and B.  Cross Product is specific to three-dimensional vectors.</ul>

In [ ]:
print("\nCross Product :\n", np.cross(arr3a,arr3b))


Cross Product :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


The cross product came 0 matrix, This is true as we made matrix b by multiplying 2 to the matrix a, meaning they both were on same plane(parallel) but cross product multiplies two perpendicular vector to generate a 3rd one perpendicular to both.

---
##4. Create a 2 dimensional array of square matrix and display of diagonal elements and also update diagonal elements with user input without using any loop.

In [ ]:
arr4=(np.arange(1,10)*2).reshape(3,3)
print("Array :\n", arr4)
print("\nDiagonal Elements :\n", arr4[range(3),range(3)]) #inbuilt options -> np.diagonal(arr4) | np.diag(arr4)
new_diagonal=[float(input(f"Enter updated diagonal element at ({i},{i}) :")) for i in range(3)] #loop still needed for entering values?
np.fill_diagonal(arr4,new_diagonal)
print("\nUpdated Array :\n",arr4)

Array :
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Diagonal Elements :
 [ 2 10 18]
Enter updated diagonal element at (0,0) :6
Enter updated diagonal element at (1,1) :6
Enter updated diagonal element at (2,2) :6

Updated Array :
 [[ 6  4  6]
 [ 8  6 12]
 [14 16  6]]


---
##5. Create a 3 dimensional array and print all elements in O(n) complexity.

In [ ]:
arr5=np.random.rand(3,3,3)*10
print("Generated 3-D Array :\n",arr5,"\n")
i,j,k=0,0,0
while (k<3):
  print(f"Element at ({k},{j},{i}) : ", arr5[k][j][i])
  i+=1
  if (i==3):
    j+=1
    i=0
  if (j==3):
    k+=1
    j=0

Generated 3-D Array :
 [[[6.20268289 1.67157355 6.54095654]
  [4.96238395 2.58069598 5.08285702]
  [2.78634195 3.25285276 9.44812229]]

 [[0.64119673 3.32591814 4.49160041]
  [1.14043837 0.59406416 0.68666898]
  [0.02811703 9.56606062 2.33300134]]

 [[2.73150293 6.88152171 9.7553881 ]
  [6.44218077 1.62358813 9.32134018]
  [4.91312714 1.07905105 7.40533395]]] 

Element at (0,0,0) :  6.20268289406968
Element at (0,0,1) :  1.671573552940746
Element at (0,0,2) :  6.540956543188738
Element at (0,1,0) :  4.962383945845021
Element at (0,1,1) :  2.5806959784419083
Element at (0,1,2) :  5.082857024153795
Element at (0,2,0) :  2.7863419514292276
Element at (0,2,1) :  3.2528527625491597
Element at (0,2,2) :  9.448122289070533
Element at (1,0,0) :  0.6411967284152253
Element at (1,0,1) :  3.3259181447692665
Element at (1,0,2) :  4.491600406264945
Element at (1,1,0) :  1.1404383735818657
Element at (1,1,1) :  0.5940641645980238
Element at (1,1,2) :  0.6866689755780209
Element at (1,2,0) :  0.02811

---
##6. Create a 2 dimensional array using user input and change it into scalar matrix and identity matrix.

In [ ]:
arr6=np.array([[(int(input(f"Enter element at ({i},{j}) : "))) for j in range(3)] for i in range(3)])
print("\nEntered 2-D Array : \n", arr6)
i,j=0,0
while (j<3):
  arr6[j][i]=1
  i+=1
  if (i==3):
    j+=1
    i=0
print("\nConverted into Scalar Matrix : \n", arr6)
i,j=0,0
while (j<3):
  if (i==j):
    arr6[j][i]=1
  else:
    arr6[j][i]=0
  i+=1
  if (i==3):
    j+=1
    i=0
print("\nConverted into Identity Matrix : \n", arr6)

Enter element at (0,0) : 1
Enter element at (0,1) : 2
Enter element at (0,2) : 3
Enter element at (1,0) : 4
Enter element at (1,1) : 5
Enter element at (1,2) : 6
Enter element at (2,0) : 7
Enter element at (2,1) : 8
Enter element at (2,2) : 9

Entered 2-D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Converted into Scalar Matrix : 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Converted into Identity Matrix : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


---
##7. Explain Inferential statistics and Descriptive statistics.

###Ans: Descriptive statistics summarizes the main features of a dataset and Inferential statistics makes predictions or draws conclusions about a population based on the observed sample data.
<ol>
  <li><b>Descriptive Statistics Techniques:
        <ul>
            <li>Measures of central tendency (mean, median, mode): Provide a central or typical value of a dataset.</li>
            <li>Measures of variability (range, variance, standard deviation): Indicate how spread out the values in a dataset are.</li>
            <li>Frequency distributions: Display the number of occurrences of different values in a dataset.</li>
            <li>Graphical representations (histograms, box plots, etc.): Visualize the distribution of data.</li>
        </ul>
  </li>
  <li><b>Inferential Statistics Techniques:
        <ul>
            <li>Hypothesis testing: Evaluates a hypothesis about a population parameter using sample data.</li>
            <li>Confidence intervals: Provides a range of values within which a population parameter is likely to fall.</li>
            <li>Regression analysis: Examines the relationship between variables and predicts the value of one variable based on another.</li>
            <li>Analysis of variance (ANOVA): Compares means of different groups to determine if there are significant differences.</li>
        </ul>
  </li>
</ol>