<H1>DAV : Lab Practicals (Numpy)
<BR>Name : DHIRENDRA KUMAR PATEL
<BR>ROLL : 16027<H1>
<H2>Q1. Write programs in Python using NumPy library to do the following:</H2>

In [2]:
import numpy as np

---
<H3>a. Create a two dimensional array, ARR1 having random values from 0 to 1. Compute the mean, standard
deviation, and variance of ARR1 along the second axis.</H3>

In [ ]:
arr1=np.random.rand(3,2)
print("Arr1 :\n",arr1)
print("\nMean of Arr1 along second axis :\n",arr1.mean(axis=1))
print("\nStandard Devication of Arr1 along second axis :\n",arr1.std(axis=1))
print("\nVariance of Arr1 along second axis :\n",arr1.var(axis=1))

Arr1 :
 [[0.52228021 0.62302632]
 [0.00143048 0.9658549 ]
 [0.82874366 0.29015905]]

Mean of Arr1 along second axis :
 [0.57265326 0.48364269 0.55945135]

Standard Devication of Arr1 along second axis :
 [0.05037305 0.48221221 0.26929231]

Variance of Arr1 along second axis :
 [0.00253744 0.23252861 0.07251835]


---
<H3>b. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and data type of
the array and then reshape it into an n x m array, where n and m are user inputs given at the run time.</H3>

In [3]:
m=int(input("Enter vaue of m :"))
n=int(input("Enter vaue of n :"))
arr2=np.random.randint(5, size=(m, n))
print("\nGenerated Array :\n", arr2)
print("\nShape : ", arr2.shape)
print("\nType : ", type(arr2))
print("\nData Type : ", arr2.dtype)
print("\nAfter reshaping :\n ", arr2.reshape(n,m))

Enter vaue of m :3
Enter vaue of n :4

Generated Array :
 [[2 3 2 2]
 [4 4 4 1]
 [4 0 0 4]]

Shape :  (3, 4)

Type :  <class 'numpy.ndarray'>

Data Type :  int64

After reshaping :
  [[2 3 2]
 [2 4 4]
 [4 1 4]
 [0 0 4]]


---
<H3>c. Test whether the elements of a given 1D array are zero, non-zero and NaN. Record the indices of these
elements in three separate arrays. </H3>

In [4]:
arr3=np.array([np.NaN,0,3,0,np.NaN,4])
print("Given 1-D Array :",arr3)
zero,nonzero,nan=[],[],[]
for x in range(len(arr3)):
    if arr3[x]==0:
      zero.append(x)
    if np.isnan(arr3[x]):
      nan.append(x)
    else:
      nonzero.append(x)
print("\nZero Indexes :",np.array(zero))
print("\nNaN Indexes :",np.array(nan))
print("\nNon-Zero Indexes :",np.array(nonzero))

Given 1-D Array : [nan  0.  3.  0. nan  4.]

Zero Indexes : [1 3]

NaN Indexes : [0 4]

Non-Zero Indexes : [1 2 3 5]


---
<H3>d. Create three random arrays of the same size: Array1, Array2 and Array3 Subtract Array 2 from Array3 and store in Array4. Create another array Array5 having two times the values in Array1. Find Covariance and Correlation of Array1 with Array4 and Array5 respectively.</H3>

In [ ]:
array1=np.random.randint(10, size=(3, 3))
array2=np.random.randint(10, size=(3, 3))
array3=np.random.randint(10, size=(3, 3))
array4=array3-array2
array5=array1*2
print("Covarience of Array1 with Array 4 :\n", np.cov(array1, array4))
print("\nCovarience of Array1 with Array 5 :\n", np.cov(array1, array5))
print("\nCorrelation of Array1 with Array 4 :\n", np.corrcoef(array1, array4))
print("\nCorrelation of Array1 with Array 5 :\n", np.corrcoef(array1, array5))

Covarience of Array1 with Array 4 :
 [[ 0.33333333 -1.33333333 -1.66666667 -0.66666667 -0.5        -0.33333333]
 [-1.33333333  9.33333333  4.66666667 -1.33333333 -7.         -0.66666667]
 [-1.66666667  4.66666667  9.33333333  5.33333333  7.          2.66666667]
 [-0.66666667 -1.33333333  5.33333333  5.33333333 10.          2.66666667]
 [-0.5        -7.          7.         10.         21.          5.        ]
 [-0.33333333 -0.66666667  2.66666667  2.66666667  5.          1.33333333]]

Covarience of Array1 with Array 5 :
 [[ 0.33333333 -1.33333333 -1.66666667  0.66666667 -2.66666667 -3.33333333]
 [-1.33333333  9.33333333  4.66666667 -2.66666667 18.66666667  9.33333333]
 [-1.66666667  4.66666667  9.33333333 -3.33333333  9.33333333 18.66666667]
 [ 0.66666667 -2.66666667 -3.33333333  1.33333333 -5.33333333 -6.66666667]
 [-2.66666667 18.66666667  9.33333333 -5.33333333 37.33333333 18.66666667]
 [-3.33333333  9.33333333 18.66666667 -6.66666667 18.66666667 37.33333333]]

Correlation of Array1 

---
<h3>e. Create two random arrays of the same size 10: Array1, and Array2. Find the sum of the first half of both the arrays and product of the second half of both the arrays.</h3>

In [ ]:
arr1=np.random.randint(100,size=10)
arr2=np.random.randint(100,size=10)
print("Array 1 :\n", arr1)
print("\nArray 2 :\n", arr2)

print("\nSum of first half of both the arrays :\n", np.sum(arr1[:5])+np.sum(arr2[:5]))
print("\nProduct of second half both the arrays :\n", np.prod(arr1[5:])*np.prod(arr2[5:]))

Array 1 :
 [49  4 76 67 91 18 55 33 77 18]

Array 2 :
 [22 85  7 42 30 60 62 45 78 60]

Sum of first half of both the arrays :
 473

Product of second half both the arrays :
 35474286687840000


---
<h3>f. Create an array with random values. Determine the size of the memory occupied by the array.</h3>

In [ ]:
arr7 = np.random.rand(4,4)
array_size = arr7.nbytes

print("Array : \n",arr7)
print("\nMemory Occupied:", array_size, "bytes")

Array : 
 [[0.27687008 0.75892354 0.35556031 0.89724933]
 [0.13901328 0.51262577 0.80823834 0.74128475]
 [0.33429883 0.93221393 0.53301149 0.60514806]
 [0.67817623 0.00671157 0.92979946 0.0696329 ]]

Memory Occupied: 128 bytes


---
<h3>g. Create a 2-dimensional array of size m x n having integer elements in the range (10,100). Write statements to swap any two rows, reverse a specified column and store updated array in another variable.</h3>

In [ ]:
m=int(input("Enter vaue of m :"))
n=int(input("Enter vaue of n :"))
arr8=np.random.randint(10,100, size=(m,n))
print("\nArray :\n",arr8)

key=1
while(key!=0):
  key=int(input("\n===============\n0. Exit \n1. Swap any two rows.\n2. Reverse a specified column.\n\nEnter choice (0-2) :"))
  if key==1:
    srow1=int(input(f"\nEnter row to be swapped [0-{m-1}] : "))
    srow2=int(input(f"\nEnter row to swap with [0-{m-1}] : "))
    temp=np.array(arr8[srow1])
    arr8[srow1]=arr8[srow2]
    arr8[srow2]=temp
    print("\nArray after swapping rows :\n",arr8)

  elif key==2:
    rcol=int(input(f"\nEnter column to be reversed [0-{n-1}]:"))
    arr9=np.array(arr8)
    arr9[:,rcol]=arr9[::-1,rcol]
    print("\nArray after reversing column :\n",arr9)

  elif key==0:
    break

Enter vaue of m :3
Enter vaue of n :4

Array :
 [[22 93 90 91]
 [52 20 50 59]
 [91 50 96 99]]

0. Exit 
1. Swap any two rows.
2. Reverse a specified column.

Enter choice (0-2) :1

Enter row to be swapped [0-2] : 2

Enter row to swap with [0-2] : 1

Array after swapping rows :
 [[22 93 90 91]
 [91 50 96 99]
 [52 20 50 59]]

0. Exit 
1. Swap any two rows.
2. Reverse a specified column.

Enter choice (0-2) :2

Enter column to be reversed [0-3]:1

Array after reversing column :
 [[22 20 90 91]
 [91 50 96 99]
 [52 93 50 59]]

0. Exit 
1. Swap any two rows.
2. Reverse a specified column.

Enter choice (0-2) :0
